language: python

python:
    - "3.4"

install: 
    - sudo apt-get install libqt4-dev
    - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
    - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
    - pip install -r requirements.txt
    - pip install flake8

script:
    - flake8
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - python -m pytest

notifications:
    email: false
