language: python
dist: trusty
python:
- '3.4'
install:
- pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
- python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
- pip install -r requirements.txt
- pip install flake8
script:
- flake8
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- python -m pytest
deploy:
  provider: pypi
  user: Jefung
  password:
    secure: UjwkhMnUmj70XRODuyHt2iReujtcioSwdbNwBg5gRzUZ5g4TNnKSSxT8U+YHmDqAhn5Shn8258H/OFneqxzrmYC2x7NUf+JgnU65G0xwzD0TWme9IjFv+fHH8KZ7s7RPAu/6K6fyG0+MGEDe3gCywR2hokudfGMqnzMKFn+j4K4dauy1/LUG0MGi5M0gHhFZ9Ux+lbl9/yb2ysSr6dJM2YQqXFZQqGHxtxWs0jFif47itrwkiCs75jFiKXeVJVCh5RWijAxqlFsgnTiE0Mf8YSxKf7PL9Q7GtGMRA3Cdgh3hTYFDqGhDsqH0a5pzORADmUlDdShVx12OctEeHD885MRM65+iUXheCR8mbR3enpf1C7f1kZ0RgnI1P+ylRqqRMEBQ9ABsZYi9MA5JwYm4rUlNWSAzoB+gT2sxcBr3tdXFfzL0CmLkQSM/ecl/r+6vMcJQtM2SCyjHdsah3FJ72yAZNnXTkI8DAI/ELryBBadjQqnJXZbBQWBth5256w5qc1FD0BywooZWTIskafbYpPDasgzoBwLTs7Xsc75IzBg89wSr0WABJQSBp2vAcHpbuvok+fP7Gw/OLdvkN7N0R6m3dnLiTH1D6o/DltIut1EfnLeSsAtrTzq5NxTLJXuHy9HGxWQm7HmEsO+JtN7dfayI4AjH/ydNlH3K1Mthi8Q=
  on:
    tags: true
    repo: KD-Group/quite
