language: python
dist: trusty
python:
- '3.4'
install:
- pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
- python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
- pip install -r requirements.txt
- pip install flake8
script:
- flake8
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- python -m pytest
deploy:
  provider: pypi
  user: 'Jefung'
  password:
    secure: D04ZZNQejPwXM74bGwp2xZv/y6k0HWRWx3Wcnw9Rri0y0H9Xb82uAk59BI+/PE8Zee9i9jsoHV15XVLvke89G2DZKyU88YCcWx8+DjwQIfzdHSGhsFkOeCSXhk29wICInANiVwRuIo1e5knPjY6g6OjVdQ/PxBbctTQTSbAR2UnVC0Dz2USS8i87ypXTLBskRmvJgTKxaNkyfs1p0mLxWxfSQP7Su5LSK+xLF3a2uSPAeOmyXv7/nYfixcYUjlTFCCTDVFyEohZ5mnBkA3QoiHbHFA9s5AdrCD1MPOPeob6CervjhgC9q7BJtYvbSb6FtXF/+eZAAhzS0CltXFEVskNMUqJO7dwFS1QOYnHKKWeY5q0PtEEFkriRQALQQPNZQ7gqmbryJHSrOC6657fuEVsjxQiYYhSk525lr3a9kV8/kA1gFkUC7/+ox0UciUQF0vLiO3wHBBLUMs74RhxMoNKqP8EnkE15cYSAeRqqZsyTd2PSCmaNdlDM6zZHtNO8q1Qsvn2tsfV87poZmwc/s0EUwmYZYpr/GmvJy+DTiO40YfGWbury62QiHck5LHvGTs0B315FtS1NqBb/glggSYbFimSTQhSlSGhsFIgfulzwF90KxtAiVgZfMgAaWhIVG2zWhLhL5EuLusXPWD1UwwvDO08qlGKshQHsGoJZVL4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: KD-Group/quite
